GET http://localhost:3001/api/notes/

###

GET http://localhost:3001/api/notes?important=false

###

GET http://localhost:3001/api/notes?search=React&important=false

###

GET http://localhost:3001/api/notes/2

###

POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsImlhdCI6MTY1OTUwNzk4M30.sWNR_GBdAwcSxmDeOID57YTywfa1jXcCmDWLchxKie0

{
    "content": "React is awesome!",
    "important": false
}

###

DELETE  http://localhost:3001/api/notes/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsImlhdCI6MTY1OTUwNzk4M30.sWNR_GBdAwcSxmDeOID57YTywfa1jXcCmDWLchxKie0

###

GET http://localhost:3001/unknown

###

PUT http://localhost:3001/api/notes/2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsImlhdCI6MTY1OTUwNzk4M30.sWNR_GBdAwcSxmDeOID57YTywfa1jXcCmDWLchxKie0

{
  "important": true
}

